### model
model_name_or_path: Qwen/Qwen2.5-Coder-0.5B-Instruct
hub_model_id: ahmedheakl/ex20_qwen2.5-0.5b-1M-stack-32kcw
export_hub_model_id: ahmedheakl/ex20_qwen2.5-0.5b-1M-stack-32kcw
push_to_hub_model_id: ex20_qwen2.5-0.5b-1M-stack-32kcw
hub_strategy: every_save
#hf_hub_token is the variable here

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: stack_32k,anghabench_32k_0,anghabench_32k_1,anghabench_32k_2
template: qwen
cutoff_len: 32000
max_samples: 500000
overwrite_cache: true
preprocessing_num_workers: 64

### output
output_dir: saves/ex20_qwen2.5-0.5b-1M-stack-32kcw
logging_steps: 10
save_steps: 500
save_total_limit: 1
plot_loss: true
overwrite_output_dir: true
push_to_hub: true
hub_always_push: true
report_to: wandb
run_name: ex20_qwen2.5-0.5b-1M-stack-32kcw

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 2
learning_rate: 1.0e-5
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 200
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 25000
